<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>build.spin.module</groupId>
        <artifactId>spin-modules</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>spin-checkstyle-module</artifactId>
    <packaging>jar</packaging>

    <name>Spin Checkstyle Module</name>

    <dependencies>
        <dependency>
            <groupId>build.spin</groupId>
            <artifactId>spin-engine</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin.module</groupId>
            <artifactId>spin-java-module</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin.module</groupId>
            <artifactId>spin-module-system-module</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spawn</groupId>
            <artifactId>spawn-jdk</artifactId>
        </dependency>
    </dependencies>
</project>