#
# File: version.properties
#
# Defines the version information for each Java Module System modules.   This allows Quark Spin to determine the
# version of Apache Maven Artifacts to retrieve for establishing Class and Module Paths when compiling, testing and
# building a module.
#
# Each property name is a GLOB pattern (to match a Java Module name), followed by = and then property value, which is
# the Apache Maven Version number.
#
# The use of GLOB patterns permit similarly defined module names, typically from a single developer/organization, to
# share the same module version (as they commonly do).
#
# See: https://en.wikipedia.org/wiki/Glob_(programming)
# See: http://maven.apache.org/pom.html
#
# NOTE: Lookup and use of this file is not yet supported (coming soon!)
#

jakarta.inject = 2.0.1
jakarta.el = 6.0.1

build.spin = 0.1.7
build.spin.* = 0.1.7

build.base.* = 0.28.0
build.codemodel.* = 0.24.0
build.serve.* = 0.7.0
build.spawn.* = 0.2.3

com.fasterxml.jackson.annotations = 2.21
com.fasterxml.jackson.databind = 2.21.2

com.graphqljava = 25.0

maven.settings = 3.9.16
maven.settings.builder = 3.9.16
maven.resolver.provider = 3.9.16

org.apache.maven.resolver = 2.0.16
org.apache.maven.resolver.* = 2.0.16

org.codehaus.plexus.interpolation = 1.29
org.codehaus.plexus.util = 3.6.1

org.assertj.core = 3.27.7

org.junit.jupiter.* = 6.0.3

org.mockito* = 2.19.0

org.slf4j* = 2.0.17
