<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>build.spin</groupId>
        <artifactId>project</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>spin-api</artifactId>
    <packaging>jar</packaging>

    <name>Spin API</name>

    <dependencies>
        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-flow</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-foundation</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-configuration</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-commandline</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-option</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-telemetry</artifactId>
        </dependency>

        <dependency>
            <groupId>build.codemodel</groupId>
            <artifactId>dependency-injection</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
        </dependency>
    </dependencies>
</project>
