<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>build.spin.module</groupId>
        <artifactId>spin-modules</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>spin-console-module</artifactId>
    <packaging>jar</packaging>

    <name>Spin Console Module</name>

    <dependencies>
        <dependency>
            <groupId>build.spin</groupId>
            <artifactId>spin-api</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-foundation</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-telemetry</artifactId>
        </dependency>

        <dependency>
            <groupId>build.codemodel</groupId>
            <artifactId>dependency-injection</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java</artifactId>
            <version>${graphql.version}</version>
        </dependency>

        <dependency>
            <groupId>io.undertow</groupId>
            <artifactId>undertow-core</artifactId>
            <version>${undertow.version}</version>
        </dependency>

        <dependency>
            <groupId>io.undertow</groupId>
            <artifactId>undertow-servlet</artifactId>
            <version>${undertow.version}</version>
        </dependency>

        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-java-kickstart</artifactId>
        </dependency>

        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-java-servlet</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>
    </dependencies>
</project>
