<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>build.spin</groupId>
        <artifactId>project</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>spin-engine</artifactId>
    <packaging>jar</packaging>

    <name>Spin Engine</name>

    <dependencies>
        <dependency>
            <groupId>build.spin</groupId>
            <artifactId>spin-api</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin</groupId>
            <artifactId>spin-common</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spawn</groupId>
            <artifactId>spawn-local-platform</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-configuration</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-flow</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-foundation</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-option</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-commandline</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-telemetry</artifactId>
        </dependency>

        <dependency>
            <groupId>build.codemodel</groupId>
            <artifactId>codemodel-foundation</artifactId>
        </dependency>

        <dependency>
            <groupId>build.codemodel</groupId>
            <artifactId>jdk-codemodel</artifactId>
        </dependency>

        <dependency>
            <groupId>build.codemodel</groupId>
            <artifactId>dependency-injection</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
