<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.1.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 https://maven.apache.org/xsd/maven-4.1.0.xsd">

    <parent/>

    <artifactId>spin-git-module</artifactId>
    <packaging>jar</packaging>

    <name>Spin Git Module</name>

    <dependencies>
        <dependency>
            <groupId>build.spin</groupId>
            <artifactId>spin-api</artifactId>
            <version>${revision}</version>
        </dependency>

    </dependencies>
</project>
