<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>build.spin.module</groupId>
        <artifactId>spin-modules</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>spin-java-module</artifactId>
    <packaging>jar</packaging>

    <name>Spin Java Module</name>

    <dependencies>
        <dependency>
            <groupId>build.spin</groupId>
            <artifactId>spin-api</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin</groupId>
            <artifactId>spin-common</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin.module</groupId>
            <artifactId>spin-clean-module</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin.module</groupId>
            <artifactId>spin-configuration-module</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin.module</groupId>
            <artifactId>spin-module-system-module</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-configuration</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-flow</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-foundation</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-io</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-option</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-table</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-telemetry</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-version</artifactId>
        </dependency>

        <dependency>
            <groupId>build.codemodel</groupId>
            <artifactId>codemodel-dependency-injection</artifactId>
        </dependency>

        <dependency>
            <groupId>build.codemodel</groupId>
            <artifactId>codemodel-jdk</artifactId>
        </dependency>

        <dependency>
            <groupId>build.codemodel</groupId>
            <artifactId>codemodel-foundation</artifactId>
        </dependency>

        <dependency>
            <groupId>build.spawn</groupId>
            <artifactId>spawn-application</artifactId>
        </dependency>

        <dependency>
            <groupId>build.spawn</groupId>
            <artifactId>spawn-jdk</artifactId>
        </dependency>

        <dependency>
            <groupId>build.spawn</groupId>
            <artifactId>spawn-local-jdk</artifactId>
        </dependency>

        <dependency>
            <groupId>build.spawn</groupId>
            <artifactId>spawn-local-platform</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-template</artifactId>
        </dependency>

        <dependency>
            <groupId>build.percolate</groupId>
            <artifactId>percolate-core</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-template-processor</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <generatedSourcesDirectory>${project.build.directory}/generated-sources/jt</generatedSourcesDirectory>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>build.base</groupId>
                            <artifactId>base-template-processor</artifactId>
                            <version>${base.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>analyze-dependencies</id>
                        <configuration>
                            <ignoredUnusedDeclaredDependencies combine.children="append">
                                <ignoredUnusedDeclaredDependency>build.base:base-template-processor</ignoredUnusedDeclaredDependency>
                            </ignoredUnusedDeclaredDependencies>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
