<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>build.spin.module</groupId>
        <artifactId>spin-modules</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>spin-java-module</artifactId>
    <packaging>jar</packaging>

    <name>Spin Java Module</name>

    <dependencies>
        <dependency>
            <groupId>build.spin</groupId>
            <artifactId>spin-api</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin</groupId>
            <artifactId>spin-common</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin.module</groupId>
            <artifactId>spin-clean-module</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin.module</groupId>
            <artifactId>spin-configuration-module</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.spin.module</groupId>
            <artifactId>spin-module-system-module</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-configuration</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-flow</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-foundation</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-io</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-option</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-table</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-telemetry</artifactId>
        </dependency>

        <dependency>
            <groupId>build.base</groupId>
            <artifactId>base-version</artifactId>
        </dependency>

        <dependency>
            <groupId>build.codemodel</groupId>
            <artifactId>dependency-injection</artifactId>
        </dependency>

        <dependency>
            <groupId>build.spawn</groupId>
            <artifactId>spawn-application</artifactId>
        </dependency>

        <dependency>
            <groupId>build.spawn</groupId>
            <artifactId>spawn-jdk</artifactId>
        </dependency>

        <dependency>
            <groupId>build.spawn</groupId>
            <artifactId>spawn-local-jdk</artifactId>
        </dependency>

        <dependency>
            <groupId>build.spawn</groupId>
            <artifactId>spawn-local-platform</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
        </dependency>

        <!-- TODO: FreeMaker support should be provided by a FreeMaker Extension (ie: Resource) -->
        <!-- we're putting this in here just for now to get jlink working -->
        <!-- we'll refactor/tidy this up after jlink is completely working -->
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
