###
# #%L
# Spin Java Module
# %%
# Copyright (C) 2026 Workday, Inc.
# %%
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# #L%
###
#
# Defines operating system specific rules to detect Java Development Kit installation paths (Java Homes).
#
# Each line in this file defines a rule (mapping) consisting of a unique operating system-specific Key,
# followed by an =, followed by a Glob-pattern for the absolute Path to a possible Java Home on the said
# operating system.
#
# Keys themselves are strings, without spaces, that consist of three parts:
#   1. A regular expression defining the operating system name (or one of the known kinds),
#   2. A @ separator,
#   3. A unique name for the key.
#
# Paths to Java Homes must be absolute. They typically contain glob patterns, allowing the definition of a variety of
# patterns for Java Homes with a single rule.
#
# Below is an example of a rule for defining possible Java Homes on macOS for zulu.
#
#   mac@zulu = /Library/Java/JavaVirtualMachines/zulu-*.jdk/Contents/Home
#
# The possible (lower-case) Operating System abbreviations are:
#
#   windows = All Microsoft Windows-based Operating Systems
#   mac = All Apple Macintosh-based Operating Systems
#   unix = All Unix-based Operating Systems (including linux, but excluding posix-based varieties)
#   posix = All Posix-based Operating Systems
#   unknown = Unknown Operating Systems
#
# For more information concerning the Operating System types, refer to the build.spin.option.OperatingSystem.Type enum

mac@default-java-home = /Library/Java/JavaVirtualMachines/jdk*.jdk/Contents/Home
mac@zulu-java-home = /Library/Java/JavaVirtualMachines/zulu-*.jdk/Contents/Home
mac@azul-java-home = /Library/Java/JavaVirtualMachines/azul-*/Contents/Home

mac@default-user-home = ${user.home}/Library/Java/JavaVirtualMachines/jdk*.jdk/Contents/Home
mac@zulu-user-home = ${user.home}/Library/Java/JavaVirtualMachines/zulu-*.jdk/Contents/Home
mac@azul-user-home = ${user.home}/Library/Java/JavaVirtualMachines/azul-*/Contents/Home

unix@standard-java-home = /usr/lib/jvm/java-*
unix@default-usr-local-java = /usr/local/*java*
unix@default-usr-local-jdk = /usr/local/*jdk*
